		quoteDatabase = [
								{	quote: "To play it safe is not to play.",
									quote_by: "Robert Altman"},
								{	quote: "Let's have some new cliches.",
									quote_by: "Samuel Goldwyn"},
								{	quote: "The ability to see beauty is the beginning of our moral sensibility. What we believe is beautiful we will not wantonly destroy.",
									quote_by: "Reverend Sean Parker Dennison"},
								{	quote: "When I was younger, I could remember anything, whether it had happened or not.",
									quote_by: "Mark Twain"},
								{	quote: "Before a war military science seems a real science, like astronomy; but after a war it seems more like astrology.",
									quote_by: "Rebecca West"},
								{	quote: "One's dignity may be assaulted, vandalized and cruelly mocked, but cannot be taken away unless it is surrendered.",
									quote_by: "Michael J. Fox"},
								{	quote: "Desire creates the power.",
									quote_by: "Raymond Holliwell"},	
								{	quote: "The 'Net is a waste of time, and that's exactly what's right about it.",
									quote_by: "William Gibson"},	
								{	quote: "He had occasional flashes of silence, that made his conversation perfectly delightful.",
									quote_by: "Sydney Smith"},	
								{	quote: "In the right light, at the right time, everything is extraordinary.",
									quote_by: "Aaron Rose"},	
								{	quote: "To get something done, a committee should consist of no more than three men, two of whom are absent.",
									quote_by: "Robert Copeland"},	
								{	quote: "Be sincere; be brief; be seated.",
									quote_by: "Franklin D. Roosevelt"},	
								{	quote: "She was conscious that the things she did were the things she had always wanted to do.",
									quote_by: "Zelda Fitzgerald"},	
								{	quote: "Here's a tip to avoid death by celebrity: First off, get a life. They can't touch you if you're out doing something interesting.",
									quote_by: "Kent Nichols and Douglas Sarine"},	
								{	quote: "Being a celebrity has taught me to hide, but being an actor has opened my soul.",
									quote_by: "Meryl Streep"},			
								{	quote: "Habit is necessary; it is the habit of having habits, of turning a trail into a rut, that must be incessantly fought against if one is to remain alive.",
									quote_by: "Edith Wharton"},		
								{	quote: "I believe that professional wrestling is clean and everything else in the world is fixed",
									quote_by: "Frank Deford"},	
								{	quote: "It gets late early out there.",
									quote_by: "Yogi Berra"},	
								{	quote: "Unlike most of you, I am not a nut.",
									quote_by: "Homer"},	
								{	quote: "A successful [software] tool is one that was used to do something undreamed of by its author.",
									quote_by: "S. C. Johnson"},	
								{	quote: "A computer lets you make more mistakes faster than any other invention, with the possible exceptions of handguns and Tequilla.",
									quote_by: "Mitch Ratcliffe"},	
								{	quote: "A language that doesn't have everything is actually easier to program in than some that do.",
									quote_by: "Dennis M. Ritchie"},	
								{	quote: "A formal parsing algorithm should not always be used.",
									quote_by: "D. Gries"},
								{	quote: "It's a good idea for diplomats to keep their word in small matters. It makes the later complete betrayals more of a surprise.",
									quote_by: "John Barnes"},		
								{	quote: "The ships hung in the sky in much the same way that bricks don't.",
									quote_by: "Douglas Adams"},			
								{	quote: "At the center of an uncertain and possibly illusionary universe there would always be tea.",
									quote_by: "Douglas Adams"},			
								{	quote: "There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable.There is another theory which states that this has already happened.",
									quote_by: "Douglas Adams"},			
								{	quote: "In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.",
									quote_by: "Douglas Adams"},			
								{	quote: "If there's anything more important than my ego around, I want it caught and shot now.",
									quote_by: "Douglas Adams"},			
								{	quote: "The first nonabsolute number is the number of people for whom the table is reserved. This will vary during the course of the first three telephone calls to the restaurant, and then bear no apparent relation to the number of people who actually turn up",
									quote_by: "Douglas Adams"},			
								{	quote: "Very few things actually get manufactured these days, because in an infinitely large Universe such as, for instance, the one in which we live, most things one could possibly imagine, and a lot of things one would rather not, grow somewhere.",
									quote_by: "Douglas Adams"},
								{	quote: "Insanity is doing the same thing over and over again and expecting different results.",
									quote_by: "Albert Einstein"},									
								{	quote: "The difference between stupidity and genius is that genius has its limits.",
									quote_by: "Albert Einstein"},
								{	quote: "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.",
									quote_by: "Albert Einstein"},
								{	quote: "A person who never made a mistake never tried anything new.",
									quote_by: "Albert Einstein"},
								{	quote: "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.",
									quote_by: "Albert Einstein"},
								{	quote: "Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves.",
									quote_by: "Albert Einstein"},
								{	quote: "The true sign of intelligence is not knowledge but imagination.",
									quote_by: "Albert Einstein"},
								{	quote: "Only two things are infinite, the universe and human stupidity, and I'm not sure about the former.",
									quote_by: "Albert Einstein"},
								{	quote: "If you can't explain it simply, you don't understand it well enough.",
									quote_by: "Albert Einstein"},
								{	quote: "We can't solve problems by using the same kind of thinking we used when we created them.",
									quote_by: "Albert Einstein"},
								{	quote: "How much wood would a woodchuck chuck If a woodchuck could chuck wood?",
									quote_by: "Unknown"},
								{	quote: "She stood on the balcony, inexplicably mimicking him hiccoughing, and amicably welcoming him home.",
									quote_by: "Unknown"},
								{	quote: "Three witches watch three Swatch watches. Which witch watch which Swatch watch?",
									quote_by: "Unknown"},
								{	quote: "Information is not knowledge.",
									quote_by: "Albert Einstein"},
								{	quote: "Never confuse motion with action.",
									quote_by: "Benjamin Franklin"},									
								{	quote: "The sea has neither meaning nor pity.",
									quote_by: "Anton Chekhov"},		
								{	quote: "Don't be so humble - you are not that great.",
									quote_by: "Golda Meir"},		
								{	quote: "Political correctness is tyranny with manners",
									quote_by: "Charlton Heston"},		
								{	quote: "When I was born I was so surprised I didn't talk for a year and a half.",
									quote_by: "Gracie Allen"},		
								{	quote: "Don't cry because it's over, smile because it happened.",
									quote_by: "Dr. Seuss"},		
								{	quote: "Be yourself; everyone else is already taken.",
									quote_by: "Oscar Wilde"},		
								{	quote: "So many books, so little time.",
									quote_by: "Frank Zappa"},		
								{	quote: "Be the change that you wish to see in the world.",
									quote_by: "Mahatma Gandhi"},		
								{	quote: "Love is full of anxious fears. ",
									quote_by: "Ovid"},		
								{	quote: "Home is where the Wi-Fi connects automatically",
									quote_by: "Unknown"},		
								{	quote: "The object of war is not to die for your country but to make the other bastard die for his.",
									quote_by: "George S. Patton"},
								{	quote: "If you know the enemy and know yourself you need not fear the results of a hundred battles.",
									quote_by: "Sun Tzu"},		
								{	quote: "The supreme art of war is to subdue the enemy without fighting.",
									quote_by: "Sun Tzu"},		
								{	quote: "A good example is far better than a good precept.",
									quote_by: "Dwight L. Moody"},		
								{	quote: "To the well-organized mind, death is but the next great adventure.",
									quote_by: "J. K. Rowling"},		
								{	quote: "No one can earn a million dollars honestly.",
									quote_by: "William Jennings Bryan"},		
								{	quote: "Clothes make the man. Naked people have little or no influence on society.",
									quote_by: "Mark Twain"},		
								{	quote: "A banker is a fellow who lends you his umbrella when the sun is shining, but wants it back the minute it begins to rain.",
									quote_by: "Mark Twain"},		
								{	quote: "Be careful about reading health books. You may die of a misprint.",
									quote_by: "Mark Twain"},		
								{	quote: "Facts are stubborn things, but statistics are more pliable.",
									quote_by: "Mark Twain"},		
								{	quote: "Fiction is obliged to stick to possibilities. Truth isn't.",
									quote_by: "Mark Twain"},		
								{	quote: "Success isn't permanent, and failure isn't fatal.",
									quote_by: "Mike Ditka"},		
								{	quote: "One repays a teacher badly if one only remains a pupil.",
									quote_by: "Nietzsche"},		
								{	quote: "Beat a man with the strength of you argument, not with the strength of your arm.",
									quote_by: "Oliver Wendell Holmes"},		
								{	quote: "Lack of money is no obstacle. Lack of an idea is an obstacle.",
									quote_by: "Ken Hakuta"},		
								{	quote: "Better to write for yourself and have no public, than to write for the public and have no self.",
									quote_by: "Cyril Connolly"},		
								{	quote: "When I die, I want to go peacefully like my grandfather did–in his sleep. Not yelling and screaming like the passengers in his car.",
									quote_by: "Bob Monkhouse"},		
								{	quote: "Always borrow money from a pessimist. He won’t expect it back.",
									quote_by: "Oscar Wilde"},
								{	quote: "Friendship is like peeing on yourself: everyone can see it, but only you get the warm feeling that it brings.",
									quote_by: "Robert Bloch"},		
								{	quote: "First the doctor told me the good news: I was going to have a disease named after me.",
									quote_by: "Steve Martin"},		
								{	quote: "The best time to give advice to your children is while they’re still young enough to believe you know what you’re talking about.",
									quote_by: "Evan Esar"},		
								{	quote: "Politicians and diapers have one thing in common. They should both be changed regularly, and for the same reason.",
									quote_by: "Unknown"},		
								{	quote: "The quick brown fox jumps over the lazy dog",
									quote_by: "Unknown"},		
								{	quote: "Critics are our friends, they tell us our faults.",
									quote_by: "Benjamin Franklin"},		
								{	quote: "In terms of the economy, look, I inherited a recession, I am ending on a recession",
									quote_by: "George W. Bush"},		
								{	quote: "I've abandoned free market principles to save the free market system.",
									quote_by: "George W. Bush"},		
								{	quote: "Anyone engaging in illegal financial transactions will be caught and persecuted.",
									quote_by: "George W. Bush"},		
								{	quote: "First of all, I don't see America having problems.",
									quote_by: "George W. Bush"},	
								{	quote: "I remember meeting a mother of a child who was abducted by the North Koreans right here in the Oval Office.",
									quote_by: "George W. Bush"},	
								{	quote: "Let's make sure that there is certainty during uncertain times in our economy.",
									quote_by: "George W. Bush"},	
								{	quote: "So long as I'm the president, my measure of success is victory, and success.",
									quote_by: "George W. Bush"},	
								{	quote: "Thank you, your Holiness. Awesome speech.",
									quote_by: "George W. Bush"},	
								{	quote: "A lot of times in politics you have people look you in the eye and tell you what's not on their mind.",
									quote_by: "George W. Bush"},	
								{	quote: "I'm also not very analytical. You know I don't spend a lot of time thinking about myself, about why I do things.",
									quote_by: "George W. Bush"},	
								{	quote: "One of the great things about books is sometimes there are some fantastic pictures.",
									quote_by: "George W. Bush"},	
								{	quote: "Neither in French nor in English nor in Mexican.",
									quote_by: "George W. Bush"},	
								{	quote: "It is clear our nation is reliant upon big foreign oil. More and more of our imports come from overseas.",
									quote_by: "George W. Bush"},	
								{	quote: "They misunderestimated me.",
									quote_by: "George W. Bush"},	
								{	quote: "I know the human being and fish can coexist peacefully.'",
									quote_by: "George W. Bush"},	
								{	quote: "See, in my line of work you got to keep repeating things over and over and over again for the truth to sink in, to kind of catapult the propaganda.",
									quote_by: "George W. Bush"},	
								{	quote: "You can fool some of the people all of the time, and those are the ones you need to concentrate on.",
									quote_by: "George W. Bush"},	
								{	quote: "The time to repair the roof is when the sun is shining.",
									quote_by: "John F. Kennedy"},	
								{	quote: "When I was a kid my parents moved a lot, but I always found them.",
									quote_by: "Rodney Dangerfield"},	
								{	quote: "You're only given a little spark of madness. You mustn't lose it.",
									quote_by: "Robin Williams"},	
								{	quote: "Cocaine is God's way of saying that you're making too much money.",
									quote_by: "Robin Williams"},	
								{	quote: "Never pick a fight with an ugly person, they've got nothing to lose.",
									quote_by: "Robin Williams"},	
								{	quote: "See, the problem is that God gives men a brain and a penis, and only enough blood to run one at a time.",
									quote_by: "Robin Williams"},	
								{	quote: "People age even when you're not looking.",
									quote_by: "Randy K. Milholland"},	
								{	quote: "The nice thing about standards is that there are so many of them to choose from.",
									quote_by: "Andrew S. Tanenbaum"},	
								{	quote: "Every decent man is ashamed of the government he lives under.",
									quote_by: "H. L. Mencken"},	
								{	quote: "It requires more courage to suffer than to die.",
									quote_by: "Napoleon Bonaparte"},	
								{	quote: "In theory, there is no difference between theory and practice; In practice, there is.",
									quote_by: "Chuck Reid"},	
								{	quote: "If you can't convince them, confuse them.",
									quote_by: "Harry S. Truman"},	
								{	quote: "Nothing in the world makes people so afraid as the influence of independent-minded people.",
									quote_by: "Albert Einstein"},	
								{	quote: "The main reason Santa is so jolly is because he knows where all the bad girls live.",
									quote_by: "George Carlin"},	
								{	quote: "Have you ever noticed that anybody driving slower than you is an idiot, and anyone going faster than you is a maniac?",
									quote_by: "George Carlin"},
								{	quote: "Inside every cynical person, there is a disappointed idealist.",
									quote_by: "George Carlin"},
								{	quote: "The reason I talk to myself is that I'm the only one whose answers I accept.",
									quote_by: "George Carlin"},
								{	quote: "Most people work just hard enough not to get fired and get paid just enough money not to quit.",
									quote_by: "George Carlin"},
								{	quote: "People who say they don't care what people think are usually desperate to have people think they don't care what people think.",
									quote_by: "George Carlin"},
								{	quote: "Atheism is a non-prophet organization.",
									quote_by: "George Carlin"},
								{	quote: "Electricity is really just organized lightning.",
									quote_by: "George Carlin"},
								{	quote: "Not only do I not know what's going on, I wouldn't know what to do about it if I did.",
									quote_by: "George Carlin"},
								{	quote: "If you can't beat them, arrange to have them beaten.",
									quote_by: "George Carlin"},					
								{	quote: "I think people should be allowed to do anything they want. We haven't tried that for a while. Maybe this time it'll work.",
									quote_by: "George Carlin"},	
								{	quote: "Death is caused by swallowing small amounts of saliva over a long period of time.",
									quote_by: "George Carlin"},	
								{	quote: "There's no present. There's only the immediate future and the recent past.",
									quote_by: "George Carlin"},	
								{	quote: "One can never know for sure what a deserted area looks like.",
									quote_by: "George Carlin"},		
								{	quote: "At a formal dinner party, the person nearest death should always be seated closest to the bathroom.",
									quote_by: "George Carlin"},		
								{	quote: "When Thomas Edison worked late into the night on the electric light, he had to do it by gas lamp or candle. I'm sure it made the work seem that much more urgent.",
									quote_by: "George Carlin"},		
								{	quote: "I believe that if life gives you lemons, you should make lemonade... And try to find somebody whose life has given them vodka, and have a party.",
									quote_by: "Ron White"},		
								{	quote: "Always end the name of your child with a vowel, so that when you yell the name will carry.",
									quote_by: "Bill Cosby"},		
								{	quote: "Women don't want to hear what you think. Women want to hear what they think - in a deeper voice.",
									quote_by: "Bill Cosby"},		
								{	quote: "Parents are not interested in justice, they're interested in peace and quiet.",
									quote_by: "Bill Cosby"},		
								{	quote: "Go to Heaven for the climate, Hell for the company.",
									quote_by: "Mark Twain"},
								{	quote: "By the time a man realizes that maybe his father was right, he usually has a son who thinks he's wrong.",
									quote_by: "Charles Wadsworth"},			
								{	quote: "Reality continues to ruin my life.",
									quote_by: "Bill Watterson"},		
								{	quote: "What can you say about a society that says that God is dead and Elvis is alive?",
									quote_by: "Irv Kupcinet"},		
								{	quote: "After dark all cats are leopards.",
									quote_by: "Native American Proverb"},		
								{	quote: "After the game, the king and the pawn go into the same box.",
									quote_by: "Italian Proverb"},		
								{	quote: "All things good to know are difficult to learn.",
									quote_by: "Greek Proverb"},		
								{	quote: "Don't open a shop unless you know how to smile.",
									quote_by: "Jewish Proverb"},		
								{	quote: "Don't run too far, you will have to return the same distance. ",
									quote_by: "Biblical Proverb"},		
								{	quote: "Our culture runs on coffee and gasoline, the first often tasting like the second.",
									quote_by: "Edward Abbey"},		
								{	quote: "Society is like a stew. If you don't stir it up every once in a while then a layer of scum floats to the top",
									quote_by: "Edward Abbey"},		
								{	quote: "Better a cruel truth than a comfortable delusion.",
									quote_by: "Edward Abbey"},		
								{	quote: "The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.",
									quote_by: "Edward Abbey"},		
								{	quote: "Anarchism is founded on the observation that since few men are wise enough to rule themselves, even fewer are wise enough to rule others.",
									quote_by: "Edward Abbey"},		
								{	quote: "If people persist in trespassing upon the grizzlies' territory, we must accept the fact that the grizzlies, from time to time, will harvest a few trespassers.",
									quote_by: "Edward Abbey"},		
								{	quote: "The best thing about graduating from the university was that I finally had time to sit on a log and read a good book.",
									quote_by: "Edward Abbey"},		
								{	quote: "A drink a day keeps the shrink away.",
									quote_by: "Edward Abbey"},		
								{	quote: "I stand for what I stand on.",
									quote_by: "Edward Abbey"},		
								{	quote: "Always forgive your enemies; nothing annoys them so much.",
									quote_by: "Oscar Wilde"},									
								{	quote: "I am so clever that sometimes I don't understand a single word of what I am saying.",
									quote_by: "Oscar Wilde"},
								{	quote: "The books that the world calls immoral are books that show the world its own shame.",
									quote_by: "Oscar Wilde"},
								{	quote: "Women are meant to be loved, not to be understood.",
									quote_by: "Oscar Wilde"},
								{	quote: "Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation",
									quote_by: "Oscar Wilde"},
								{	quote: "I don't want to go to heaven. None of my friends are there",
									quote_by: "Oscar Wilde"},
								{	quote: "I am not young enough to know everything",
									quote_by: "Oscar Wilde"},
								{	quote: "A thing is not necessarily true because a man dies for it",
									quote_by: "Oscar Wilde"},
								{	quote: "Experience is merely the name men gave to their mistakes.",
									quote_by: "Oscar Wilde"},
								{	quote: "I think God, in creating man, somewhat overestimated his ability.",
									quote_by: "Oscar Wilde"},
								{	quote: "Quotation is a serviceable substitute for wit.",
									quote_by: "Oscar Wilde"},
								{	quote: "Only dull people are brilliant at breakfast.",
									quote_by: "Oscar Wilde"},
								{	quote: "Whenever people agree with me I always feel I must be wrong.",
									quote_by: "Oscar Wilde"},
								{	quote: "One should always be a little improbable.",
									quote_by: "Oscar Wilde"},	
								{	quote: "A gentleman is one who never hurts anyone's feelings unintentionally.",
									quote_by: "Oscar Wilde"},	
								{	quote: "There is only one class in the community that thinks more about money than the rich, and that is the poor.",
									quote_by: "Oscar Wilde"},	
								{	quote: "A mind is like a parachute. It doesn't work if it is not open.",
									quote_by: "Frank Zappa"},	
								{	quote: "Without music to decorate it, time is just a bunch of boring production deadlines or dates by which bills must be paid.",
									quote_by: "Frank Zappa"},	
								{	quote: "Art is making something out of nothing, and selling it.",
									quote_by: "Frank Zappa"},	
								{	quote: "Communism doesn't work because people like to own stuff.",
									quote_by: "Frank Zappa"},	
								{	quote: "All the good music has already been written by people with wigs and stuff.",
									quote_by: "Frank Zappa"},	
								{	quote: "Government is the Entertainment division of the military-industrial complex",
									quote_by: "Frank Zappa"},	
								{	quote: "The most important thing to do in your life is to not interfere with somebody else's life.",
									quote_by: "Frank Zappa"},	
								{	quote: "Writing about music is like dancing about architecture.",
									quote_by: "Frank Zappa"},	
								{	quote: "The only difference between a cult and a religion is the amount of real estate they own",
									quote_by: "Frank Zappa"},	
								{	quote: "There are more love songs than anything else. If songs could make you do something we'd all love one another",
									quote_by: "Frank Zappa"},	
								{	quote: "Most rock journalism is people who can't write, interviewing people who can't talk, for people who can't read",
									quote_by: "Frank Zappa"},	
								{	quote: "One size does not fit all.",
									quote_by: "Frank Zappa"},	
								{	quote: "I wrote a song about dental floss but did anyone's teeth get cleaner?",
									quote_by: "Frank Zappa"},	
								{	quote: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
									quote_by: "Maya Angelou"},	
								{	quote: "I'm not upset that you lied to me, I'm upset that from now on I can't believe you.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "There is always some madness in love. But there is also always some reason in madness.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "Every deep thinker is more afraid of being understood than of being misunderstood.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "There are two different types of people in the world, those who want to know, and those who want to believe.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "All truly great thoughts are conceived while walking.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "Perhaps I know best why it is man alone who laughs, he alone suffers so deeply that he had to invent laughter.",
									quote_by: "Friedrich Nietzsche"},	
								{	quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
									quote_by: "Ralph Waldo Emerson"},	
								{	quote: "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.",
									quote_by: "Marilyn Monroe"},	
								{	quote: "The fool doth think he is wise, but the wise man knows himself to be a foo",
									quote_by: "William Shakespeare"},	
								{	quote: "Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.",
									quote_by: "William Shakespeare"},	
								{	quote: "I would challenge you to a battle of wits, but I see you are unarmed!",
									quote_by: "William Shakespeare"},	
								{	quote: "We know what we are, but not what we may be.",
									quote_by: "William Shakespeare"},	
								{	quote: "All the world's a stage, And all the men and women merely players.",
									quote_by: "William Shakespeare"},	
								{	quote: "The course of true love never did run smooth.",
									quote_by: "William Shakespeare"},	
								{	quote: "I like this place and could willingly waste my time in it.",
									quote_by: "William Shakespeare"},	
								{	quote: "To weep is to make less the depth of grief.",
									quote_by: "William Shakespeare"},	
								{	quote: "Expectation is the root of all heartache.",
									quote_by: "William Shakespeare"},	
								{	quote: "Listen to many, speak to a few.",
									quote_by: "William Shakespeare"},	
								{	quote: "Love is the greatest of dreams, yet the worst of nightmares.",
									quote_by: "William Shakespeare"},	
								{	quote: "Look like the innocent flower, But be the serpent under it.",
									quote_by: "William Shakespeare"}									

								];