		quoteDatabase = [
								{	quote: "To play it safe is not to play.",
									quote_by: "Robert Altman"},
								{	quote: "Let's have some new cliches.",
									quote_by: "Samuel Goldwyn"},
								{	quote: "The ability to see beauty is the beginning of our moral sensibility. What we believe is beautiful we will not wantonly destroy.",
									quote_by: "Reverend Sean Parker Dennison"},
								{	quote: "When I was younger, I could remember anything, whether it had happened or not.",
									quote_by: "Mark Twain"},
								{	quote: "Before a war military science seems a real science, like astronomy; but after a war it seems more like astrology.",
									quote_by: "Rebecca West"},
								{	quote: "One's dignity may be assaulted, vandalized and cruelly mocked, but cannot be taken away unless it is surrendered.",
									quote_by: "Michael J. Fox"},
								{	quote: "Desire creates the power.",
									quote_by: "Raymond Holliwell"},	
								{	quote: "The 'Net is a waste of time, and that's exactly what's right about it.",
									quote_by: "William Gibson"},	
								{	quote: "He had occasional flashes of silence, that made his conversation perfectly delightful.",
									quote_by: "Sydney Smith"},	
								{	quote: "In the right light, at the right time, everything is extraordinary.",
									quote_by: "Aaron Rose"},	
								{	quote: "To get something done, a committee should consist of no more than three men, two of whom are absent.",
									quote_by: "Robert Copeland"},	
								{	quote: "Be sincere; be brief; be seated.",
									quote_by: "Franklin D. Roosevelt"},	
								{	quote: "She was conscious that the things she did were the things she had always wanted to do.",
									quote_by: "Zelda Fitzgerald"},	
								{	quote: "Here's a tip to avoid death by celebrity: First off, get a life. They can't touch you if you're out doing something interesting.",
									quote_by: "Kent Nichols and Douglas Sarine"},	
								{	quote: "Being a celebrity has taught me to hide, but being an actor has opened my soul.",
									quote_by: "Meryl Streep"},			
								{	quote: "Habit is necessary; it is the habit of having habits, of turning a trail into a rut, that must be incessantly fought against if one is to remain alive.",
									quote_by: "Edith Wharton"},		
								{	quote: "I believe that professional wrestling is clean and everything else in the world is fixed",
									quote_by: "Frank Deford"},	
								{	quote: "It gets late early out there.",
									quote_by: "Yogi Berra"},	
								{	quote: "Unlike most of you, I am not a nut.",
									quote_by: "Homer"},	
								{	quote: "A successful [software] tool is one that was used to do something undreamed of by its author.",
									quote_by: "S. C. Johnson"},	
								{	quote: "A computer lets you make more mistakes faster than any other invention, with the possible exceptions of handguns and Tequilla.",
									quote_by: "Mitch Ratcliffe"},	
								{	quote: "A language that doesn't have everything is actually easier to program in than some that do.",
									quote_by: "Dennis M. Ritchie"},	
								{	quote: "A formal parsing algorithm should not always be used.",
									quote_by: "D. Gries"},
								{	quote: "It's a good idea for diplomats to keep their word in small matters. It makes the later complete betrayals more of a surprise.",
									quote_by: "John Barnes"},		
								{	quote: "The ships hung in the sky in much the same way that bricks don't.",
									quote_by: "Douglas Adams"},			
								{	quote: "At the center of an uncertain and possibly illusionary universe there would always be tea.",
									quote_by: "Douglas Adams"},			
								{	quote: "There is a theory which states that if ever anyone discovers exactly what the Universe is for and why it is here, it will instantly disappear and be replaced by something even more bizarre and inexplicable.There is another theory which states that this has already happened.",
									quote_by: "Douglas Adams"},			
								{	quote: "In the beginning the Universe was created. This has made a lot of people very angry and been widely regarded as a bad move.",
									quote_by: "Douglas Adams"},			
								{	quote: "If there's anything more important than my ego around, I want it caught and shot now.",
									quote_by: "Douglas Adams"},			
								{	quote: "The first nonabsolute number is the number of people for whom the table is reserved. This will vary during the course of the first three telephone calls to the restaurant, and then bear no apparent relation to the number of people who actually turn up",
									quote_by: "Douglas Adams"},			
								{	quote: "Very few things actually get manufactured these days, because in an infinitely large Universe such as, for instance, the one in which we live, most things one could possibly imagine, and a lot of things one would rather not, grow somewhere.",
									quote_by: "Douglas Adams"},
								{	quote: "Insanity is doing the same thing over and over again and expecting different results.",
									quote_by: "Albert Einstein"},									
								{	quote: "The difference between stupidity and genius is that genius has its limits.",
									quote_by: "Albert Einstein"},
								{	quote: "The world is a dangerous place to live; not because of the people who are evil, but because of the people who don't do anything about it.",
									quote_by: "Albert Einstein"},
								{	quote: "A person who never made a mistake never tried anything new.",
									quote_by: "Albert Einstein"},
								{	quote: "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.",
									quote_by: "Albert Einstein"},
								{	quote: "Any man who can drive safely while kissing a pretty girl is simply not giving the kiss the attention it deserves.",
									quote_by: "Albert Einstein"},
								{	quote: "The true sign of intelligence is not knowledge but imagination.",
									quote_by: "Albert Einstein"},
								{	quote: "Only two things are infinite, the universe and human stupidity, and I'm not sure about the former.",
									quote_by: "Albert Einstein"},
								{	quote: "If you can't explain it simply, you don't understand it well enough.",
									quote_by: "Albert Einstein"},
								{	quote: "We can't solve problems by using the same kind of thinking we used when we created them.",
									quote_by: "Albert Einstein"},
								{	quote: "How much wood would a woodchuck chuck If a woodchuck could chuck wood?",
									quote_by: "Unknown"},
								{	quote: "She stood on the balcony, inexplicably mimicking him hiccoughing, and amicably welcoming him home.",
									quote_by: "Unknown"},
								{	quote: "Three witches watch three Swatch watches. Which witch watch which Swatch watch?",
									quote_by: "Unknown"},
								{	quote: "Information is not knowledge.",
									quote_by: "Albert Einstein"},
								{	quote: "Never confuse motion with action.",
									quote_by: "Benjamin Franklin"},									
								{	quote: "The sea has neither meaning nor pity.",
									quote_by: "Anton Chekhov"},		
								{	quote: "Don't be so humble - you are not that great.",
									quote_by: "Golda Meir"},		
								{	quote: "Political correctness is tyranny with manners",
									quote_by: "Charlton Heston"},		
								{	quote: "When I was born I was so surprised I didn't talk for a year and a half.",
									quote_by: "Gracie Allen"},		
								{	quote: "Don't cry because it's over, smile because it happened.",
									quote_by: "Dr. Seuss"},		
								{	quote: "Be yourself; everyone else is already taken.",
									quote_by: "Oscar Wilde"},		
								{	quote: "So many books, so little time.",
									quote_by: "Frank Zappa"},		
								{	quote: "Be the change that you wish to see in the world.",
									quote_by: "Mahatma Gandhi"},		
								{	quote: "Love is full of anxious fears. ",
									quote_by: "Ovid"},		
								{	quote: "Home is where the Wi-Fi connects automatically",
									quote_by: "Unknown"},		
								{	quote: "The object of war is not to die for your country but to make the other bastard die for his.",
									quote_by: "George S. Patton"}									
		
								];